# Generated by Django 5.2.3 on 2026-03-01 04:58

import django.core.validators
import django.db.models.deletion
import users.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('email', models.EmailField(db_index=True, error_messages={'blank': '%(field_name)s cannot be blank.', 'invalid': 'Enter a valid %(field_name_lower)s address.', 'null': '%(field_name)s cannot be null.', 'required': '%(field_name)s is required.'}, max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='Email address')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Phone number')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2, message='First name must be at least 2 characters long.')], verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2, message='First name must be at least 2 characters long.')], verbose_name='Last name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10, null=True, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, null=True, validators=[users.validators.DateOfBirthValidator], verbose_name='Date of birth')),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True, verbose_name='Blood Group')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Users/ProfileImage/', validators=[users.validators.ImageValidator], verbose_name='Profile Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verification')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Verification Time')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Phone Verification')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Phone Verification Time')),
                ('auth_provider', models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedIn', 'LinkedIn'), ('gitHub', 'GitHub')], default='local', max_length=20, verbose_name='Authentication With')),
                ('fcm_device_token', models.TextField(blank=True, null=True, verbose_name='Device Token')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible JSON field to store additional user-related information.', null=True, verbose_name='Metadata')),
                ('last_activity', models.DateTimeField(blank=True, help_text="Timestamp of the user's last activity on the system.", null=True, verbose_name='Last Activity')),
                ('signup_ip', models.GenericIPAddressField(blank=True, help_text='IP address from which the user signed up.', null=True, verbose_name='Signup IP Address')),
                ('signup_source', models.CharField(blank=True, help_text='Source platform or method used for user signup (e.g., web, mobile app).', max_length=50, null=True, verbose_name='Signup Source')),
                ('timezone', models.CharField(default='UTC', help_text="User's preferred timezone for displaying times and dates.", max_length=50, verbose_name='Timezone')),
                ('language_preference', models.CharField(default='en', help_text="User's preferred language for the system interface.", max_length=10, verbose_name='Language Preference')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Indicates whether two-factor authentication is enabled for the user.', verbose_name='Two-Factor Authentication Enabled')),
                ('password_changed_at', models.DateTimeField(blank=True, help_text='Timestamp when the user last changed their password.', null=True, verbose_name='Password Changed At')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed login attempts.', verbose_name='Failed Login Attempts')),
                ('lockout_until', models.DateTimeField(blank=True, help_text='Timestamp until which the user account is locked due to multiple failed login attempts.', null=True, verbose_name='Lockout Until')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created Person')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.religion', verbose_name='User Religion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated Person')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('otp', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000, message='OTP must be a 6-digit number.'), django.core.validators.MaxValueValidator(999999, message='OTP must be a 6-digit number.')], verbose_name='OTP Code')),
                ('token', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Token must be a valid 64-character string.', regex='^[A-Za-z0-9-_]{64}$')], verbose_name='Token')),
                ('is_otp_used', models.BooleanField(default=False, verbose_name='Is OTP Used')),
                ('is_token_used', models.BooleanField(default=False, verbose_name='Is Token Used')),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created Person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated Person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User OTP',
                'verbose_name_plural': 'User OTPs',
            },
        ),
    ]
