# Generated by Django 5.2.3 on 2026-03-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Stock Keeping Unit (SKU)'),
        ),
    ]
