# Generated by Django 5.2.3 on 2026-03-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
