# Generated by Django 5.2.3 on 2026-03-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_variant_per_product',
        ),
    ]
