# Generated by Django 5.2.3 on 2026-03-01 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Country Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Country Code')),
                ('capital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capital')),
                ('region', models.CharField(blank=True, max_length=5, null=True, verbose_name='Region')),
                ('cur_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency Code')),
                ('cur_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency Name')),
                ('cur_symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency Symbol')),
                ('lan_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Language Code')),
                ('lan_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Language Name')),
                ('dia_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Dialling Code')),
                ('iso_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='ISO Code')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='Flag')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Religion Name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReligionDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=50, verbose_name='Denomination Name')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='core.religion', verbose_name='Religion')),
            ],
            options={
                'unique_together': {('religion', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RichTextEditorMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('file', models.FileField(upload_to='richtext/', verbose_name='Media File')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('file', 'File')], editable=False, max_length=10, verbose_name='File Type')),
                ('size', models.PositiveIntegerField(editable=False, null=True, verbose_name='File Size (bytes)')),
                ('mime_type', models.CharField(editable=False, max_length=100, verbose_name='Mime Type')),
                ('original_name', models.CharField(editable=False, max_length=255, verbose_name='Original Name')),
                ('checksum', models.CharField(db_index=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Checksum')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'unique_together': {('checksum', 'content_type', 'object_id')},
            },
        ),
    ]
