# Generated by Django 5.2.3 on 2026-03-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person'),
        ),
    ]
