# Generated by Django 5.2.3 on 2026-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Supplier Company Name'),
        ),
    ]
