# Generated by Django 5.2.3 on 2026-03-04 03:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('invoice_no', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Order Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14, verbose_name='Grand Total')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Expire Date')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
